description: >
  The executor for continuations
docker:
  - image: 'cimg/base:<<parameters.tag>>'
parameters:
  tag:
    default: stable
    description: >
      Pick a specific circleci/base image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
